; KeyToggles v2.0

[General]
; To retrieve the title of the game's window, you have 2 solutions:
;
; Method 1
; 1. Launch your game in windowed mode.
; 2. The name of the window will be displayed on the left side of the title bar.
;
; Method 2
; 1. Launch your game
; 2. Tab out.
; 3. Open Task Manager.
; 4. Go to the Processes tab.
; 5. Expand the entry corresponding to your game.
; 6. The name of the window will be one of the expanded entries.
windowName="put_window_name_here"

; How much time (in milliseconds) to wait before sending another input in autofire mode
autofireKeyDelay=100

; Fixes common system key combinations (such as Alt+Tab) not working when toggle keys are modifiers (1 to enable)
fixSystemKeys=1

; How much time (in milliseconds) to wait before checking if the window is active (again)
; If the window is no longer active, all keys will be released
focusCheckDelay=1000

; How much time (in milliseconds) to wait before hooking the window once it becomes active
; Increase this delay if the window you're trying to hook isn't the right one (causing hotkeys not to work)
hookDelay=0

; How much time (in milliseconds) to wait between key press and release in hold/autofire/autofire hold mode
; Increase this delay in case keystrokes aren't registered in some games
keyDelay=0

; Restore toggles to their previous state when the window regains focus (1 to enable)
restoreTogglesOnFocus=0

; Restore autofires to their previous state when the window regains focus (1 to enable)
restoreAutofiresOnFocus=0

; Force the script to run as admin (1 to enable)
runAsAdmin=0

; Show notifications when certain events (such as window hooking) occur (1 to enable)
showNotifications=0

; Use these to set key modes individually
; 0: disable
; 1: toggle (for keys that must be held down)
; 2: hold (for keys that only work as toggles)
; 3: autofire toggle (pressed by toggling the autofire keys)
; 4: autofire hold (pressed by holding the autofire keys)
aimMode=1
crouchMode=1
sprintMode=4

; See https://www.autohotkey.com/docs/KeyList.htm for key IDs
[Keys]
; Main keys (disabled if set to autofire mode)
aimKey=RButton
crouchKey=LControl
sprintKey=LShift

; Autofire keys (disabled if not set to autofire mode)
; Repeatedly simulate pressing the corresponding main key
; until pressed again (autofire toggle mode)
; until released (autofire hold mode)
aimAutofireKey=F1
crouchAutofireKey=F2
sprintAutofireKey=F3

[Debug]
; Enable debug functions such as closing (ALT+F10) or reloading (ALT+F11) the script (1 to enable)
debugMode=0