; KeyToggles v2.0

[General]
; Name of the process to hook (mandatory, case sensitive)
; To retrieve the process name:

; 1. Open Task Manager.
; 2. Go to the Processes tab.
; 3. Right click the entry corresponding to your game.
; 4. Select "Go to details".
; 5. The name of the process will be highlighted in the Details tab.
processName=""

; Title of the window to hook (optional, case sensitive)
; To retrieve the title of the game's window, you have 2 solutions:

; Method 1
; 1. Launch your game in windowed mode.
; 2. The name of the window will be displayed on the left side of the title bar.

; Method 2
; 1. Launch your game
; 2. Tab out.
; 3. Open Task Manager.
; 4. Go to the Processes tab.
; 5. Expand the entry corresponding to your game.
; 6. The name of the window will be one of the expanded entries.

; Method 3
; Use Window Spy (included with AutoHotkey).
windowName=""

; How much time (in milliseconds) to wait before sending another input in autofire mode
autofireKeyInterval=100

; Fixes common system key combinations (such as Alt+Tab) not working when toggle keys are modifiers (0 to disable)
fixSystemKeys=1

; How much time (in milliseconds) to wait before checking if the window is active (again)
; If the window is no longer active, all keys will be released
focusCheckInterval=1000

; How much time (in milliseconds) to wait before hooking the window once it becomes active
; Increase this delay if the window you're trying to hook isn't the right one (or use windowName)
hookDelay=0

; How much time (in milliseconds) to wait between key press and release in hold/autofire/autofire hold modes
; Increase this delay in case keystrokes aren't registered in some games
keyDelay=0

; Restores toggles to their previous state when the window regains focus (1 to enable)
restoreTogglesOnFocus=0

; Restores autofire toggles to their previous state when the window regains focus (1 to enable)
restoreAutofiresOnFocus=0

; Forces the script to run as admin (1 to enable)
runAsAdmin=0

; Shows notifications when certain events (such as window hooking) occur
; 0: disabled
; 1: system notifications
; 2: tooltips
showNotifications=0

; Use these to set key modes individually
; 0: disabled
; 1: toggle (converts keys that must be held down into toggle keys)
; 2: hold (converts keys that must be toggled into hold keys)
; 3: autofire toggle (pressed by toggling the autofire key)
; 4: autofire hold (pressed by holding the autofire key)
; 5: autorun (press once to start autorunning, press again to stop)
aimMode=0
crouchMode=0
sprintMode=0
autorunMode=0

; See https://www.autohotkey.com/docs/KeyList.htm for key IDs
[Keys]
; Main keys (automatically disabled if set to autofire mode)
aimKey=RButton
crouchKey=LControl
sprintKey=LShift

; Autorun keys (automatically disabled if not set to autorun mode)
; Autorunning is automatically disengaged when pressing the forward or backward key
autorunKey=F1
forwardKey=w
backwardKey=s

; Autofire keys (automatically disabled if not set to autofire mode)
; Repeatedly simulates pressing the corresponding main key until pressed again (autofire toggle mode)
; Repeatedly simulates pressing the corresponding main key while held down (autofire hold mode)
aimAutofireKey=F2
crouchAutofireKey=F3
sprintAutofireKey=F4

[Debug]
; Enables debug traces (you'll need https://www.autohotkey.com/docs/v2/lib/OutputDebug.htm#Remarks to see them)
; and advanced functions such as closing (ALT + F10) or reloading (ALT + F11) the script (1 to enable)
debugMode=0