; KeyToggles v2.4

[General]
; Name of the process to hook (mandatory, case sensitive)
; To retrieve the name of the process, you have 2 solutions:

; Method 1
; Use the built-in configurator and click the Browse button at the top.

; Method 2
; 1. Open Task Manager.
; 2. Go to the Processes tab.
; 3. Right click the entry corresponding to your game.
; 4. Select "Go to details".
; 5. The name of the process will be highlighted in the Details tab.
processName=""

; Title of the window to hook (optional, case sensitive)
; To retrieve the title of the game's window, you have 4 solutions:

; Method 1
; Use the built-in configurator and click the Select button at the top.

; Method 2
; 1. Run the game in windowed mode.
; 2. The name of the window will be displayed on the left side of the title bar.

; Method 3
; 1. Run the game.
; 2. Tab out.
; 3. Open Task Manager.
; 4. Go to the Processes tab.
; 5. Expand the entry corresponding to your game.
; 6. The name of the window will be one of the expanded entries.

; Method 4
; Use Window Spy (included with AutoHotkey).
windowName=""

; How much time (in milliseconds) to wait before sending another input in autofire mode
autofireKeyInterval=100

; Fixes common system key combinations (such as Alt+Tab) not working when toggle keys are modifiers (0 to disable)
fixSystemKeys=1

; How much time (in milliseconds) to wait before checking if the window is active (again)
; If the window is no longer active, all keys will be released
focusCheckInterval=1000

; How much time (in milliseconds) to wait before hooking the window once it becomes active
; Increase this delay if the window you're trying to hook isn't the right one (or use windowName)
hookDelay=0

; How much time (in milliseconds) to wait between key press and release in hold/autofire/autofire hold modes
; Increase this delay in case keystrokes aren't registered in some games
keyDelay=25

; Restores autofire toggles to their previous state when the window regains focus (1 to enable)
restoreAutofiresOnFocus=0

; Restores toggles to their previous state when the window regains focus (1 to enable)
restoreTogglesOnFocus=0

; Forces the script to run as admin (1 to enable)
runAsAdmin=0

; Shows notifications when certain events occur (only works in windowed mode)
; 0: disabled
; 1: system notifications
; 2: tooltips
showNotifications=0

; Use these to set key modes individually
; 0: disabled
; 1: toggle (converts keys that must be held down into toggle keys)
; 2: hold (converts keys that must be toggled into hold keys)
; 3: autofire toggle (pressed by toggling the corresponding autofire key)
; 4: autofire hold (pressed by holding the corresponding autofire key)
aimMode=0
crouchMode=0
sprintMode=0

; 0: disabled
; 1: autorun (press once to start autorunning, press again to stop)
autorunMode=0

; See https://www.autohotkey.com/docs/v2/KeyList.htm for key IDs
[Keys]
; Main keys (automatically disabled if set to autofire mode)
; Even though their name suggests their typical use case, they can be set to perform other actions (ex: jump)
aimKey=RButton
crouchKey=LControl
sprintKey=LShift

; Autorun keys (disabled if not set to autorun mode)
; Autorunning is automatically disengaged when pressing the forward or backward key
autorunKey=F1
forwardKey=w
backwardKey=s

; Autofire keys (disabled if not set to autofire mode)
; Repeatedly simulates pressing the corresponding main key until pressed again (autofire toggle mode)
; Repeatedly simulates pressing the corresponding main key while held down (autofire hold mode)
aimAutofireKey=F2
crouchAutofireKey=F3
sprintAutofireKey=F4

[UI]
; Keep the GUI on top of other windows (1 to enable)
alwaysOnTop=0

; Close the GUI to the system tray instead of exiting (1 to enable)
closeToTray=0

; Use dark mode for the GUI (1 to enable)
darkMode=1

; Hide the selector window from screen capture programs as it could contain undesirable processes (1 to enable)
hideFromCapture=1

; Minimize the GUI to the system tray instead of the taskbar (1 to enable)
minimizeToTray=1

; Restore the GUI position at launch (1 to enable, centered on screen otherwise)
rememberWindowPosition=0
windowX=0
windowY=0

[Debug]
; Enables debug traces (you'll need https://www.autohotkey.com/docs/v2/lib/OutputDebug.htm#Remarks to see them)
; and advanced functions such as closing (ALT + F10) or reloading (ALT + F11) the script (1 to enable)
debugMode=0